### PR TITLE
Fix login

### PR DESCRIPTION
**Pull request by leana8959**
Hello,

I managed to update the deprecated functions, switched to explicit waits, now it's possible to log in to Twitter! (and a bit faster too)

However, the like function is still not working, I'm afraid I'm lacking some of the expertise here... If you'd like to, you can check out the branch "fix-like".

Have a nice day.

### CODE REVIEW

**Review by shubhayu-64 — CHANGES_REQUESTED** [review]
Hi @leana8959, I went through your PR and I would request a few changes. 
- Try using relative paths and not absolute paths for login function because they tend to break easily on minor UI changes.

Please elaborate on the issue you have with the like function. Attach errors and anything relevant.

**Comment by leana8959** [comment]
>  Try using relative paths and not absolute paths for login function because they tend to break easily on minor UI changes.

Sure, I'll do that. Could you tell me how to find relative path though?

**Comment by shubhayu-64** [comment]
> 
The idea is to not use an absolute path from "/html/div/div/..." but like "//img[@alt='LambdaTest']" 

Here is an in-depth guide on the same: https://www.lambdatest.com/blog/complete-guide-for-using-xpath-in-selenium-with-examples/

**Comment by leana8959** [comment]
I'm not sure what I'm doing wrong here, I don't know enough to figure this out myself, it'd be awesome if I could ask you some more questions !

The input field in HTML looks like this.
```html
<input autocapitalize="sentences" autocomplete="username" autocorrect="on" name="text" spellcheck="true" type="text" dir="auto" class="r-30o5oe r-1niwhzg r-17gur6a r-1yadl64 r-deolkf r-homxoj r-poiln3 r-7cikom r-1ny4l3l r-t60dpp r-1dz5y72 r-fdjqy7 r-13qz1uu" value="">
```

I tried to use a relative XPATH `input[@name='text' and @autocomplete='username']` to reach the field, but it doesn't work. How can I make this work?

**Comment by shubhayu-64** [comment]
> I'm not sure what I'm doing wrong here, I don't know enough to figure this out myself, it'd be awesome if I could ask you some more questions !
> 
> The input field in HTML looks like this.
> 
> ```
> <input autocapitalize="sentences" autocomplete="username" autocorrect="on" name="text" spellcheck="true" type="text" dir="auto" class="r-30o5oe r-1niwhzg r-17gur6a r-1yadl64 r-deolkf r-homxoj r-poiln3 r-7cikom r-1ny4l3l r-t60dpp r-1dz5y72 r-fdjqy7 r-13qz1uu" value="">
> ```
> 
> I tried to use a relative XPATH `input[@name='text' and @autocomplete='username']` to reach the field, but it doesn't work. How can I make this work?

Try using tags which are unique to that specific target. In this case try looking for class name that is unique to this input tag.

**Comment by leana8959** [comment]
Thank you for your help.
By class name, you mean `r-30o5oe r-1niwhzg r-17gur6a r-1yadl64 r-deolkf r-homxoj r-poiln3 r-7cikom r-1ny4l3l r-t60dpp r-1dz5y72 r-fdjqy7 r-13qz1uu`?
I also don't understand why selenium can't find the element, while pasting the same xpath Firefox works perfectly.

**Comment by shubhayu-64** [comment]
> 

Yes, all class names are separated by a space, you can find a unique one and just use that.

**Comment by leana8959** [comment]
I tried to use `input[@class='r-17gur6a]` and `input[@name='username' and @class='r-17gur6a]`, neither of them worked. Also I tried to search that specific class in Firefox, it's unique.

**Comment by shubhayu-64** [comment]
> I tried to use `input[@class='r-17gur6a]` and `input[@name='username' and @class='r-17gur6a]`, neither of them worked. Also I tried to search that specific class in Firefox, it's unique.

I think the functions have changes in the newer versions of Selenium. Take a look at this code snippet from selenium documentation: https://selenium-python.readthedocs.io/locating-elements.html
```python
from selenium.webdriver.common.by import By

driver.find_element(By.XPATH, '//button[text()="Some text"]')
driver.find_elements(By.XPATH, '//button')
```

**Comment by leana8959** [comment]
In the end, `(By.NAME, "username")` worked for the username field.
However, the next button looks like this 

```html
<div dir="ltr" class="css-901oao r-1awozwy r-6koalj r-18u37iz r-16y2uox r-37j5jr r-a023e6 r-b88u0q r-1777fci r-rjixqe r-bcqeeo r-q4m81j r-qvutc0" style="color: rgb(15, 20, 25);"><span class="css-901oao css-16my406 css-1hf3ou5 r-poiln3 r-a023e6 r-rjixqe r-bcqeeo r-qvutc0"><span class="css-901oao css-16my406 r-poiln3 r-bcqeeo r-qvutc0">Next</span></span></div>
```

There's no name attribute to use, and I notice that the class name changes at page reload, I imagine that's some kind of obfuscation. What's the best way to overcome this, then?

**Comment by shubhayu-64** [comment]
> 
I guess sending a RETURN keystroke after the username will do the work.

**Review by shubhayu-64 — APPROVED** [review]
Looks good to me.

**Comment by shubhayu-64** [comment]
Please create an issue about your login function

**Comment by leana8959** [comment]
You mean `like_tweets()` function? Will do that.

**Pull request merged**
